package mods.eln

import mods.eln.entity.ReplicatorPopProcess
import mods.eln.ghost.GhostManager
import mods.eln.i18n.I18N.tr
import mods.eln.init.Config
import mods.eln.init.ElnContent
import mods.eln.init.Items
import mods.eln.item.MiningPipeDescriptor
import mods.eln.item.electricalinterface.ItemEnergyInventoryProcess
import mods.eln.misc.FunctionTable
import mods.eln.misc.Obj3DFolder
import mods.eln.misc.Utils
import mods.eln.misc.WindProcess
import mods.eln.node.NodeBlockEntity
import mods.eln.node.NodeManager
import mods.eln.node.NodePublishProcess
import mods.eln.node.six.SixNode
import mods.eln.node.six.SixNodeItem
import mods.eln.node.transparent.TransparentNode
import mods.eln.node.transparent.TransparentNodeItem
import mods.eln.packets.*
import mods.eln.server.*
import mods.eln.sim.Simulator
import mods.eln.sim.ThermalLoadInitializer
import mods.eln.sixnode.lampsupply.LampSupplyElement
import mods.eln.sixnode.modbusrtu.ModbusTcpServer
import mods.eln.sixnode.powersocket.PowerSocketElement
import mods.eln.sixnode.tutorialsign.TutorialSignElement
import mods.eln.sixnode.wirelesssignal.IWirelessSignalSpot
import mods.eln.sixnode.wirelesssignal.tx.WirelessSignalTxElement
import mods.eln.transparentnode.teleporter.TeleporterElement
import net.minecraft.command.ServerCommandManager
import net.minecraft.creativetab.CreativeTabs
import net.minecraft.init.Blocks
import net.minecraft.item.Item
import net.minecraft.item.ItemArmor
import net.minecraft.item.ItemStack
import net.minecraftforge.fml.common.FMLCommonHandler
import net.minecraftforge.fml.common.Mod
import net.minecraftforge.fml.common.SidedProxy
import net.minecraftforge.fml.common.event.*
import net.minecraftforge.fml.common.network.FMLEventChannel
import net.minecraftforge.fml.common.network.NetworkRegistry
import net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper
import net.minecraftforge.fml.relauncher.Side
import net.minecraftforge.fml.relauncher.SideOnly
import org.apache.logging.log4j.Logger

/**
 * Main mod class for Electrical Age: Re-Wired
 * Implements 1.12.2 Forge API pattern with Kotlin
 */
@Mod(
    modid = Eln.MODID,
    version = Eln.VERSION,
    name = Eln.NAME,
    dependencies = Eln.DEPENDENCIES,
    acceptedMinecraftVersions = Eln.ACCEPTABLE_MINECRAFT_VERSION,
    acceptableSaveVersions = Eln.ACCEPTABLE_SAVE_VERSIONS
)
class Eln {

    /**
     * Pre-initialization phase - called before any content is registered.
     * Initialize logger, config, simulator, and prepare content for registration.
     */
    @Mod.EventHandler
    fun preInit(e: FMLPreInitializationEvent) {
        val metadata = e.modMetadata
        metadata.authorList = AUTHORS.toMutableList()
        metadata.description = tr("mod.meta.desc")
        metadata.url = URL
        metadata.autogenerated = false

        // Initialize proxy (registers renderers on client)
        proxy?.preInit(e)

        // Initialize logger first (needed by ElnContent)
        logger = e.modLog
        logger.info(tr("Bzzzt"))

        // Load configuration (already loaded by Forge via @Config annotation)
        loadConfiguration()

        // Start the simulator (needed before creating cable descriptors)
        simulator = Simulator(
            0.05,
            1.0 / Config.electricalFrequency,
            Config.electricalInterSystemOverSampling,
            1.0 / Config.thermalFrequency
        )

        // Load 3D models BEFORE initializing content (needed for descriptors)
        obj.loadAllElnModels()

        // Initialize content using 1.12.2 registration pattern
        // Blocks and items are created here, registered via RegistryEvent
        ElnContent.preInit()

        // Initialize network channels
        initNetwork()

        // Initialize managers
        playerManager = PlayerManager()
        nodeManager = NodeManager("$MODID.nodes")
        ghostManager = GhostManager("$MODID.ghosts")
        delayedTaskManager = DelayedTaskManager()

        logger.info("Electrical Age pre-initialization complete")
    }

    /**
     * Initialization phase - called after blocks/items are registered.
     * Register tile entities, entities, recipes, and other content.
     */
    @Mod.EventHandler
    fun init(e: FMLInitializationEvent) {
        // Initialize proxy (registers renderers on client)
        proxy?.init(e)

        NetworkRegistry.INSTANCE.registerGuiHandler(instance, GuiHandler())

        // Initialize tile entities, entities, and other content
        ElnContent.init()

        regenOreScannerFactors()

        // Register with Waila for integration
        registerWailaIntegration()

        // Initialize ore dictionary integration
        initOreDictionary()

        logger.info("Electrical Age initialization complete")
    }

    /**
     * Post-initialization phase - called after all mods are loaded.
     * Check for mod compatibility and finalize setup.
     */
    @Mod.EventHandler
    fun postInit(event: FMLPostInitializationEvent) {
        serverEventListener = ServerEventListener()

        // Check for mod compatibility
        checkModCompatibility()

        // Verify recipes
        checkRecipes()

        logger.info("Electrical Age post-initialization complete")
    }

    /**
     * Called when server is about to start.
     * Initialize simulator state and server-side systems.
     */
    @Mod.EventHandler
    fun onServerStart(e: FMLServerAboutToStartEvent) {
        clearSimulatorState()

        simulator.reinit()

        // Initialize Modbus server if enabled
        if (Config.modbusEnable) {
            modbusServer = ModbusTcpServer(Config.modbusPort)
        }

        // Add slow processes to simulator
        simulator.apply {
            addSlowProcess(windProcess)
            addSlowProcess(replicatorPopProcess)
            addSlowProcess(itemEnergyInventoryProcess)
            addSlowProcess(nodePublishProcess)
        }

        logger.info("Electrical Age server starting")
    }

    /**
     * Called when server is starting.
     * Register commands and load world-specific data.
     */
    @Mod.EventHandler
    fun onServerStarting(e: FMLServerStartingEvent) {
        val server = FMLCommonHandler.instance().minecraftServerInstance
        val command = server.commandManager
        val manager = command as ServerCommandManager
        manager.registerCommand(ConsoleListener())

        simulator.start()

        logger.info("Electrical Age server started")
    }

    /**
     * Called when server is stopped.
     * Clean up server-side resources.
     */
    @Mod.EventHandler
    fun onServerStopped(e: FMLServerStoppedEvent) {
        // Each step is isolated: under Cleanroom the classloader can refuse to
        // load a not-yet-loaded class (e.g. DelayedBlockRemove) during teardown,
        // which previously threw out of this handler and HUNG the game on close.
        // Wrapping every step guarantees shutdown always completes cleanly.
        fun safe(label: String, action: () -> Unit) {
            try {
                action()
            } catch (t: Throwable) {
                logger.warn("Electrical Age server-stop: '$label' failed, continuing shutdown: $t")
            }
        }

        safe("modbus") { modbusServer?.destroy() }
        safe("simulatorState") { clearSimulatorState() }
        safe("nodeManager") { nodeManager.clear() }
        safe("ghostManager") { ghostManager.clear() }
        safe("delayedTask") { delayedTaskManager.clear() }
        safe("delayedBlockRemove") { DelayedBlockRemove.clear() }
        safe("serverEvent") { serverEventListener.clear() }
        safe("simulator") { simulator.stop() }

        logger.info("Electrical Age server stopped")
    }

    /**
     * Load configuration values from Config.kt
     */
    private fun loadConfiguration() {
        // Configuration is automatically loaded by Forge via @Config annotation
        // Apply config values to mod fields
        maxSoundDistance = Config.maxSoundDistance
        fuelHeatValueFactor = Config.fuelHeatValueFactor
        plateConversionRatio = Config.plateConversionRatio
        stdBatteryHalfLife = Config.stdBatteryHalfLife
        batteryCapacityFactor = Config.batteryCapacityFactor
        wailaEasyMode = Config.wailaEasyMode
        explosionEnable = Config.explosionEnable
        forceOreRegen = Config.forceOreRegen
        debugEnabled = Config.debugEnable
        versionCheckEnabled = true // Could add config option if needed
        analyticsEnabled = Config.analyticsEnabled
        playerUUID = Config.playerUUID
        killMonstersAroundLamps = false // Could add config option
        killMonstersAroundLampsRange = 8 // Could add config option
        noSymbols = false // Could add config option
        noVoltageBackground = false // Could add config option
    }

    /**
     * Initialize network channels and packet handlers
     */
    private fun initNetwork() {
        // Simple network wrapper for packet handling
        elnNetwork = NetworkRegistry.INSTANCE.newSimpleChannel(simpleChannelId)
        elnNetwork.registerMessage(TransparentNodeRequestPacketHandler::class.java, TransparentNodeRequestPacket::class.java, 1, Side.SERVER)
        elnNetwork.registerMessage(TransparentNodeResponsePacketHandler::class.java, TransparentNodeResponsePacket::class.java, 2, Side.CLIENT)
        elnNetwork.registerMessage(GhostNodeWailaRequestPacketHandler::class.java, GhostNodeWailaRequestPacket::class.java, 3, Side.SERVER)
        elnNetwork.registerMessage(GhostNodeWailaResponsePacketHandler::class.java, GhostNodeWailaResponsePacket::class.java, 4, Side.CLIENT)
        elnNetwork.registerMessage(SixNodeWailaRequestPacketHandler::class.java, SixNodeWailaRequestPacket::class.java, 5, Side.SERVER)
        elnNetwork.registerMessage(SixNodeWailaResponsePacketHandler::class.java, SixNodeWailaResponsePacket::class.java, 6, Side.CLIENT)
        elnNetwork.registerMessage(GenericPacketHandler::class.java, GenericPacket::class.java, 7, Side.CLIENT)
        elnNetwork.registerMessage(GenericPacketHandler::class.java, GenericPacket::class.java, 8, Side.SERVER)

        packetHandler = PacketHandler()
    }

    /**
     * Register Waila integration for tooltip display
     */
    private fun registerWailaIntegration() {
        try {
            // Send message to Waila to register our callback
            FMLInterModComms.sendMessage("Waila", "register", "mods.eln.integration.waila.WailaIntegration.callbackRegister")
            logger.info("Waila integration registered")
        } catch (e: Exception) {
            logger.warn("Waila not available, skipping integration")
        }
    }

    /**
     * Initialize ore dictionary integration
     */
    private fun initOreDictionary() {
        // Ore dictionary handling will be done in ElnContent
        // This is called after blocks/items are registered
    }

    /**
     * Check for mod compatibility and set flags accordingly
     */
    private fun checkModCompatibility() {
        // Check for ComputerCraft
        Other.check()

        // Check for other mods and enable/disable features accordingly
        // This is where we'd handle IC2, OpenComputers, etc.
    }

    /**
     * Check if all items have recipes and log warnings for missing ones
     */
    private fun checkRecipes() {
        // This would iterate through all registered descriptors and check for recipes
        // Implementation depends on how recipes are registered
        logger.info("Recipe check complete")
    }

    /**
     * Clear simulator state on server start/stop
     */
    private fun clearSimulatorState() {
        TutorialSignElement.resetBalise()
        TeleporterElement.teleporterList.clear()
        NodeBlockEntity.clientList.clear()
        WirelessSignalTxElement.channelMap.clear()
        IWirelessSignalSpot.spots.clear()
        LampSupplyElement.channelMap.clear()
        PowerSocketElement.channelMap.clear()
        playerManager.clear()
    }

    companion object {
        @JvmStatic
        @Mod.Instance(MODID)
        lateinit var instance: Eln

        const val MODID = "eln"
        const val VERSION = mods.eln.misc.Version.VERSION_STRING
        const val ACCEPTABLE_SAVE_VERSIONS = "[2.0)"
        const val ACCEPTABLE_MINECRAFT_VERSION = "1.12.2"
        const val NAME = "Electrical Age: Re-Wired"
        const val DEPENDENCIES = "required-after:forge"
        const val URL = "https://github.com/brambora69123/electrical-age-rewired"
        const val UPDATE_URL = "https://github.com/brambora69123/electrical-age-rewired/releases"
        const val SRC_URL = "https://github.com/brambora69123/electrical-age-rewired"

        @JvmField
        val AUTHORS = arrayOf("brambora69123", "Dolu1990", "lambdaShade", "cm0x4D", "metc", "Baughn")

        /**
         * Client proxy - initialized by Forge via @SidedProxy
         */
        @SidedProxy(
            clientSide = "mods.eln.client.ClientProxy",
            serverSide = "mods.eln.CommonProxy"
        )
        @JvmField
        var proxy: CommonProxy? = null

        // =====================================================================
        // Stateless helper processes
        // =====================================================================
        @JvmField
        val windProcess = WindProcess()

        @JvmField
        val replicatorPopProcess = ReplicatorPopProcess()

        @JvmField
        val itemEnergyInventoryProcess = ItemEnergyInventoryProcess()

        @JvmField
        val nodePublishProcess = NodePublishProcess()

        // =====================================================================
        // Initialized in event handlers
        // =====================================================================
        @JvmStatic
        lateinit var logger: Logger

        @JvmStatic
        lateinit var simulator: Simulator

        @JvmField
        var modbusServer: ModbusTcpServer? = null

        @JvmStatic
        lateinit var serverEventListener: ServerEventListener

        @JvmStatic
        lateinit var playerManager: PlayerManager

        @JvmStatic
        lateinit var nodeManager: NodeManager

        @JvmStatic
        lateinit var ghostManager: GhostManager

        @JvmStatic
        lateinit var delayedTaskManager: DelayedTaskManager

        // =====================================================================
        // Network channels
        // =====================================================================
        @JvmStatic
        lateinit var elnNetwork: SimpleNetworkWrapper

        const val simpleChannelId = "eln"

        @JvmStatic
        lateinit var packetHandler: PacketHandler

        // =====================================================================
        // Items and Blocks
        // =====================================================================
        @JvmStatic
        lateinit var sharedItem: mods.eln.generic.SharedItem

        @JvmStatic
        lateinit var sharedItemStackOne: mods.eln.generic.SharedItem

        @JvmStatic
        lateinit var sixNodeItem: SixNodeItem

        @JvmStatic
        lateinit var transparentNodeItem: TransparentNodeItem

        @JvmStatic
        lateinit var miningPipeDescriptor: MiningPipeDescriptor

        // Standalone Items
        @JvmField
        var swordCopper: Item? = null
        @JvmField
        var hoeCopper: Item? = null
        @JvmField
        var shovelCopper: Item? = null
        @JvmField
        var pickaxeCopper: Item? = null
        @JvmField
        var axeCopper: Item? = null

        @JvmField
        var helmetCopper: ItemArmor? = null
        @JvmField
        var plateCopper: ItemArmor? = null
        @JvmField
        var legsCopper: ItemArmor? = null
        @JvmField
        var bootsCopper: ItemArmor? = null

        @JvmField
        var helmetECoal: ItemArmor? = null
        @JvmField
        var plateECoal: ItemArmor? = null
        @JvmField
        var legsECoal: ItemArmor? = null
        @JvmField
        var bootsECoal: ItemArmor? = null

        // Packet type constants
        const val packetPlayerKey: Byte = 14
        const val packetNodeSingleSerialized: Byte = 15
        const val packetPublishForNode: Byte = 16
        const val packetOpenLocalGui: Byte = 17
        const val packetForClientNode: Byte = 18
        const val packetPlaySound: Byte = 19
        const val packetDestroyUuid: Byte = 20
        const val packetClientToServerConnection: Byte = 21
        const val packetServerToClientInfo: Byte = 22

        // =====================================================================
        // Rendering
        // =====================================================================
        @JvmField
        val obj = Obj3DFolder()

        // =====================================================================
        // Physical constants and configuration
        // =====================================================================
        val batteryVoltageFunctionTable = FunctionTable(
            doubleArrayOf(0.000, 0.9, 1.0, 1.025, 1.04, 1.05, 2.0),
            6.0 / 5.0
        )

        const val cableHeatingTime = 30.0
        const val cableWarmLimit = 130.0
        const val cableThermalConductionTao = 0.5

        val cableThermalLoadInitializer = ThermalLoadInitializer(
            cableWarmLimit, -100.0, cableHeatingTime, cableThermalConductionTao
        )

        val sixNodeThermalLoadInitializer = ThermalLoadInitializer(
            cableWarmLimit, -100.0, cableHeatingTime, 1000.0
        )

        // =====================================================================
        // Configuration values (loaded from Config.kt)
        // =====================================================================
        var maxSoundDistance = 16.0
        var fuelHeatValueFactor = 0.0000675
        var plateConversionRatio = 1
        var stdBatteryHalfLife = 2 * Utils.minecraftDay
        var batteryCapacityFactor = 1.0
        var wailaEasyMode = false
        var explosionEnable = false
        var forceOreRegen = false
        var debugEnabled = false
        var versionCheckEnabled = true
        var analyticsEnabled = true
        var playerUUID: String? = null
        var killMonstersAroundLamps = false
        var killMonstersAroundLampsRange = 8
        var noSymbols = false
        @JvmField
        var noVoltageBackground = false

        @JvmField
        val oreScannerConfig = ArrayList<mods.eln.item.electricalitem.PortableOreScannerItem.RenderStorage.OreScannerConfigElement>()

        fun regenOreScannerFactors() {
            oreScannerConfig.clear()

            // Add vanilla ores
            val vanillaOres = mapOf(
                net.minecraft.init.Blocks.COAL_ORE to 0.05f,
                net.minecraft.init.Blocks.IRON_ORE to 0.15f,
                net.minecraft.init.Blocks.GOLD_ORE to 0.40f,
                net.minecraft.init.Blocks.LAPIS_ORE to 0.40f,
                net.minecraft.init.Blocks.REDSTONE_ORE to 0.40f,
                net.minecraft.init.Blocks.DIAMOND_ORE to 1.0f,
                net.minecraft.init.Blocks.EMERALD_ORE to 0.40f
            )

            for ((block, factor) in vanillaOres) {
                oreScannerConfig.add(mods.eln.item.electricalitem.PortableOreScannerItem.RenderStorage.OreScannerConfigElement(net.minecraft.block.Block.getIdFromBlock(block), factor))
            }

            // Add Eln ores
            val elnOres = mapOf(
                mods.eln.init.ModBlock.copperOreBlock to 0.15f,
                mods.eln.init.ModBlock.leadOreBlock to 0.15f,
                mods.eln.init.ModBlock.tungstenOreBlock to 0.15f,
                mods.eln.init.ModBlock.cinnabarOreBlock to 0.15f
            )

            for ((block, factor) in elnOres) {
                oreScannerConfig.add(mods.eln.item.electricalitem.PortableOreScannerItem.RenderStorage.OreScannerConfigElement(net.minecraft.block.Block.getIdFromBlock(block), factor))
            }

            // NOW update the mapping table
            mods.eln.item.electricalitem.OreColorMapping.updateColorMapping()
        }

        // =====================================================================
        // Creative Tab
        // =====================================================================
        @JvmField
        val Tab = object : CreativeTabs("eln") {
            @SideOnly(Side.CLIENT)
            override fun createIcon(): ItemStack {
                // Use the Electrical Vu Meter as the tab icon (was a plain redstone block).
                try {
                    val item = sixNodeItem
                    if (item != null) {
                        for (desc in item.subItemList.values) {
                            if (desc is mods.eln.generic.GenericItemBlockUsingDamageDescriptor
                                && "Electrical Vu Meter" == desc.name) {
                                val st = desc.newItemStack()
                                if (st != null && !st.isEmpty) return st
                            }
                        }
                    }
                } catch (t: Throwable) {
                    logger.warn("Eln tab icon lookup failed, using fallback: $t")
                }
                return ItemStack(Blocks.REDSTONE_BLOCK)
            }
        }
    }
}
